// Generated by CoffeeScript 1.9.1
var Promise, Waffel, _, async, cheerio, colors, fs, glob, i18n, markdown, marked, moment, nunjucks, path, util, yaml,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

_ = require('lodash');

colors = require('colors');

Promise = require('bluebird');

path = require('path');

util = require('util');

async = require('async');

yaml = require('yaml-front-matter');

fs = Promise.promisifyAll(require('fs-extra'));

glob = Promise.promisifyAll(require('globby'));

i18n = require('i18next');

moment = require('moment');

nunjucks = require('nunjucks');

markdown = require('nunjucks-markdown');

marked = require('marked');

cheerio = require('cheerio');

module.exports = Waffel = (function() {
  Waffel.prototype.brunchPlugin = true;

  Waffel.prototype.defaults = {
    verbose: true,
    defaultPagination: 10,
    defaultSortField: 'slug',
    defaultSortOrder: 'desc',
    structureFile: 'site.yml',
    viewFolder: 'views',
    dataFolder: 'data',
    destinationFolder: 'public',
    staticFolder: 'assets',
    localesFolder: 'locales',
    domain: '',
    assetPath: '',
    root: process.cwd(),
    ext: '.md',
    templateExt: '.html',
    languages: [],
    defaultLanguage: 'en',
    fallbackLanguage: 'en',
    sitemap: true,
    uglyUrls: false,
    dateFormat: 'YYYY-MM-DD',
    helpers: {},
    filters: {}
  };

  Waffel.prototype.helpers = {
    url: function(name, data, options) {
      var page;
      if (data == null) {
        data = {};
      }
      if (options == null) {
        options = {};
      }
      page = this._getPageByName(name);
      if (options.page) {
        page.pagination = {
          page: options.page
        };
      }
      return _.compact([this.options.domain, this._url(page, data, options), 'index.html']).join('/');
    },
    asset: function(_path) {
      if (_path == null) {
        _path = '';
      }
      return _.compact([this.options.domain, this.options.assetPath, _path]).join('/');
    },
    absoluteURL: function(url) {
      return _.compact([this.options.domain, url]).join('/');
    },
    t: function(key, page) {
      return i18n.translate(key, {
        lng: page.language
      });
    }
  };

  Waffel.prototype.filters = {
    toArray: function(object) {
      return _.toArray(object);
    },
    pluck: function(object, key) {
      if (object == null) {
        object = {};
      }
      return _.pluck(object, key);
    },
    flatten: function(array) {
      if (array == null) {
        array = [];
      }
      return _.flatten(array);
    },
    uniq: function(array) {
      if (array == null) {
        array = [];
      }
      return _.uniq(array);
    },
    where: function(array, search) {
      if (array == null) {
        array = [];
      }
      if (search == null) {
        search = {};
      }
      return _.where(array, search);
    },
    limit: function(array, count) {
      if (array == null) {
        array = [];
      }
      if (count == null) {
        count = 10;
      }
      return array.slice(0, count);
    },
    format: function(date, format) {
      if (format == null) {
        format = this.options.dateFormat;
      }
      return moment(date).format(format);
    },
    excerpt: function(text, size) {
      var $, words;
      if (size == null) {
        size = 200;
      }
      $ = cheerio.load(marked(text));
      text = $('p').filter(function(index, element) {
        return (element.children[0].type === 'text') || _.contains(['em', 'strong'], element.children[0].name);
      }).first().text().trim();
      if (text.length > size) {
        words = text.substring(0, size).split(' ');
        words.pop();
        return (words.join(' ')) + "…";
      } else {
        return text;
      }
    },
    toJSON: function(data) {
      return JSON.stringify(data);
    },
    inspect: function(object) {
      console.log(util.inspect(object, false, 2, true));
      return object;
    }
  };

  function Waffel(opts) {
    this.postGenerate = bind(this.postGenerate, this);
    var filter, helper, name, ref, ref1, site;
    this.options = _.extend(this.defaults, opts);
    this.options.dataFolder = path.join(this.options.root, this.options.dataFolder);
    this.options.viewFolder = path.join(this.options.root, this.options.viewFolder);
    this.options.staticFolder = path.join(this.options.root, this.options.staticFolder);
    this.options.localesFolder = path.join(this.options.root, this.options.localesFolder);
    this.options.destinationFolder = path.join(this.options.root, this.options.destinationFolder);
    this.options.structureFile = path.join(this.options.root, this.options.structureFile);
    this.helpers = _.extend(this.helpers, this.options.helpers);
    this.filters = _.extend(this.filters, this.options.filters);
    ref = this.helpers;
    for (name in ref) {
      helper = ref[name];
      this.helpers[name] = _.bind(helper, this);
    }
    ref1 = this.filters;
    for (name in ref1) {
      filter = ref1[name];
      this.filters[name] = _.bind(filter, this);
    }
    this.filters.excerpt = _.memoize(this.filters.excerpt, function(text, size) {
      return (text.substring(0, 16)) + "." + size;
    });
    this.data = {};
    site = yaml.safeLoad(fs.readFileSync(this.options.structureFile, 'utf8'));
    this.config = site.config;
    this.structure = site.structure;
    this.registerTemplates();
  }

  Waffel.prototype.registerTemplates = function() {
    var filter, name, ref;
    this.env = nunjucks.configure(this.options.viewFolder, {
      watch: false,
      express: null
    });
    ref = this.filters;
    for (name in ref) {
      filter = ref[name];
      this.env.addFilter(name, filter.bind(this));
    }
    markdown.register(this.env, marked);
    return nunjucks.precompile(this.options.viewFolder, {
      env: this.env
    });
  };

  Waffel.prototype.init = function() {
    var _path;
    _path = path.join(this.options.dataFolder, "**/*" + this.options.ext);
    console.log("--> Globbing " + _path.cyan + ":");
    i18n.init({
      preload: this.options.languages.concat(['dev']),
      lng: this.options.defaultLanguage,
      fallbackLng: 'dev',
      resGetPath: path.join(this.options.localesFolder, '__lng__.json')
    });
    return glob.callAsync(this, _path).then((function(_this) {
      return function(files) {
        files.forEach(_this._parseFile, _this);
        return _this.data;
      };
    })(this));
  };

  Waffel.prototype.generate = function() {
    this.start = process.hrtime();
    console.log("--> Start generation process...\n---");
    return fs.ensureDirAsync(this.options.destinationFolder).then((function(_this) {
      return function() {
        var i, language, len, ref, tasks;
        tasks = [];
        ref = _this.options.languages;
        for (i = 0, len = ref.length; i < len; i++) {
          language = ref[i];
          tasks = tasks.concat(_this._generateForLanguage(language, true));
        }
        tasks = tasks.concat(_this._generateForLanguage(_this.options.defaultLanguage, false));
        return async.parallel(tasks, _this.postGenerate);
      };
    })(this));
  };

  Waffel.prototype.postGenerate = function(err, pages) {
    var elapsed, millis;
    elapsed = process.hrtime(this.start);
    millis = elapsed[1] / 1000000;
    console.log("--> Generated " + (pages.length + '').cyan + " pages in " + elapsed[0] + "." + (millis.toFixed(0)) + "s.");
    if (this.options.sitemap) {
      return this._createSitemap(pages);
    }
  };

  Waffel.prototype._generateForLanguage = function(language, localised) {
    var _name, _page, name, page, ref, ref1, tasks, url;
    tasks = [];
    ref = this.structure;
    for (name in ref) {
      page = ref[name];
      if (page.template) {
        page.name = name;
        url = this._url(page, {}, {
          language: language,
          localised: localised
        });
        tasks.push(this._createPage(page, name, url, {}, language, localised));
      } else if (page.collection) {
        ref1 = page.pages;
        for (_name in ref1) {
          _page = ref1[_name];
          _page.name = name + "." + _name;
          if (_name === 'single') {
            tasks = tasks.concat(this._createSinglePages(_page, name + ".single", this.data[page.collection], language, localised));
          } else {
            tasks = tasks.concat(this._createCollectionPage(_page, name + "." + _name, this.data[page.collection], language, localised));
          }
        }
      }
    }
    return tasks;
  };

  Waffel.prototype._parseFile = function(file) {
    var base, base1, collection, data, language, name1, ref, relativePath, tokens;
    relativePath = file.replace(this.options.dataFolder, '');
    tokens = relativePath.split(path.sep).slice(1);
    collection = tokens[0];
    (base = this.data)[collection] || (base[collection] = {});
    data = yaml.loadFront(file);
    data.slug = data.slug || path.basename(relativePath, this.options.ext);
    if (ref = tokens[1], indexOf.call(this.options.languages, ref) >= 0) {
      language = tokens[1];
      (base1 = this.data[collection])[name1 = data.slug] || (base1[name1] = {
        _localised: true
      });
      return this.data[collection][data.slug][language] = data;
    } else {
      return this.data[collection][data.slug] = data;
    }
  };

  Waffel.prototype._getPageByName = function(name) {
    var tokens;
    tokens = name.split('.');
    if (tokens.length === 1) {
      return this.structure[name];
    } else {
      return this.structure[tokens[0]].pages[tokens[1]];
    }
  };

  Waffel.prototype._slugify = function(value) {
    if (value == null) {
      value = '';
    }
    return value.toLowerCase().replace(/\s+/g, '-').replace(/[^-\w]/g, '');
  };

  Waffel.prototype._formatToken = function(value) {
    if (value instanceof Date) {
      value = moment(value).format(this.options.dateFormat);
    }
    return this._slugify(value);
  };

  Waffel.prototype._url = function(page, data, opts) {
    var tokens;
    if (opts == null) {
      opts = {};
    }
    tokens = page.url.split('/');
    if (opts.localised) {
      tokens.unshift(opts.language);
    }
    tokens = tokens.map((function(_this) {
      return function(token) {
        if (token[0] === ':') {
          return _this._formatToken(data.group || data[token.slice(1)]);
        } else {
          return token;
        }
      };
    })(this));
    if (page.pagination && page.pagination.page > 1) {
      tokens.push('page');
      tokens.push(page.pagination.page);
    }
    return _.compact(tokens).join('/');
  };

  Waffel.prototype._target = function(url) {
    var ext;
    ext = path.extname(url);
    if (ext) {
      return path.join(this.options.destinationFolder, url);
    } else if (this.options.uglyUrls && url.length > 0) {
      return path.join(this.options.destinationFolder, url + ".html");
    } else {
      return path.join(this.options.destinationFolder, url, 'index.html');
    }
  };

  Waffel.prototype._renderPage = function(page, item) {
    return nunjucks.render("" + page.template + this.options.templateExt, _.extend(this.helpers, {
      options: this.options,
      config: this.config,
      data: this.data,
      page: page,
      item: item
    }));
  };

  Waffel.prototype._createCollectionPage = function(page, name, set, language, localised) {
    var order, sets, sort, tasks;
    sort = page.sort && page.sort.field ? page.sort.field : this.options.defaultSortField;
    order = page.sort && page.sort.order ? page.sort.order : this.options.defaultSortOrder;
    if (page.groupBy) {
      sets = {};
      _(set).pluck(page.groupBy).flatten().unique().sort().value().forEach((function(_this) {
        return function(group) {
          return sets[group] = _.toArray(set).filter(function(x) {
            if (_(x[page.groupBy]).isArray()) {
              return _.contains(x[page.groupBy], group);
            } else {
              return x[page.groupBy] === group;
            }
          });
        };
      })(this));
    } else {
      sets = [set];
    }
    tasks = _.map(sets, (function(_this) {
      return function(set, group) {
        var pages;
        pages = _(set).sortBy(sort).tap(function(x) {
          if (order === 'desc') {
            return _(x.reverse());
          } else {
            return x;
          }
        }).chunk(page.paginate || _this.options.defaultPagination).value();
        return pages.map(function(p, index) {
          var _page, url;
          _page = _.clone(page);
          _page.pagination = {
            page0: index,
            page: index + 1,
            total: pages.length
          };
          _page.group = group;
          url = _this._url(_page, {
            group: group
          }, {
            language: language,
            localised: localised
          });
          return _this._createPage(_page, name, url, p, language, localised);
        });
      };
    })(this));
    return _.flatten(tasks);
  };

  Waffel.prototype._createSinglePages = function(page, name, set, language, localised) {
    return _.map(set, (function(_this) {
      return function(item, slug) {
        var data, url;
        data = item._localised ? item[language] || item[_this.options.fallbackLanguage] : item;
        url = _this._url(page, data, {
          language: language,
          localised: localised
        });
        return _this._createPage(page, name, url, data, language, localised);
      };
    })(this));
  };

  Waffel.prototype._createPage = function(page, name, url, data, language, localised) {
    if (data == null) {
      data = {};
    }
    return (function(_this) {
      return function(callback) {
        var _page, languageInfo, output, pageInfo, paginationInfo, target;
        target = _this._target(url);
        _page = _.clone(page);
        _page.language = language;
        _page.localised = localised;
        output = _this._renderPage(_page, data);
        languageInfo = localised ? "[" + language + "] " : '[--] ';
        paginationInfo = page.pagination ? " " + page.pagination.page + "/" + page.pagination.total : '';
        pageInfo = data.slug || data.group || page.group || '';
        pageInfo = pageInfo ? " [" + pageInfo + "]" : '';
        if (_this.options.verbose) {
          console.log(languageInfo.red + "Generating " + name.green + pageInfo.yellow + paginationInfo.magenta + " at: " + target.cyan);
        }
        return fs.outputFile(target, output, function(err) {
          return callback(err, {
            page: _page,
            data: data,
            url: url
          });
        });
      };
    })(this);
  };

  Waffel.prototype._createSitemap = function(pages) {
    var output, target;
    target = path.join(this.options.destinationFolder, 'sitemap.xml');
    output = nunjucks.render('sitemap.xml', _.extend(this.helpers, {
      options: this.options,
      config: this.config,
      data: this.data,
      pages: pages,
      now: new Date
    }));
    return fs.outputFile(target, output, (function(_this) {
      return function(err) {
        return console.log("--> Created " + 'sitemap.xml'.cyan);
      };
    })(this));
  };

  return Waffel;

})();
