// Generated by CoffeeScript 1.11.1
var MarkdownEngine, _, marked;

_ = require('lodash');

marked = require('marked');

module.exports = MarkdownEngine = (function() {
  MarkdownEngine.prototype.defaults = {
    gfm: true,
    tables: true,
    smartLists: true,
    smartypants: false
  };

  function MarkdownEngine(opts) {
    this.options = _.extend({}, this.defaults, opts);
    marked.setOptions(this.options);
  }

  MarkdownEngine.prototype.getRenderer = function() {
    return marked;
  };

  return MarkdownEngine;

})();
