// Generated by CoffeeScript 1.10.0
var path;

path = require('path');

module.exports = {
  relativisePath: function(filePath, basePath) {
    if (filePath == null) {
      filePath = '';
    }
    if (basePath == null) {
      basePath = '';
    }
    filePath = path.normalize(filePath);
    basePath = path.normalize(basePath);
    return path.sep + path.relative(basePath, filePath);
  }
};
